/*
 * Generated by dtrace(1M).
 */

#ifndef	_FRENCHKITPROVIDER_H
#define	_FRENCHKITPROVIDER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define FRENCHKIT_STABILITY "___dtrace_stability$frenchkit$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define FRENCHKIT_TYPEDEFS "___dtrace_typedefs$frenchkit$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	FRENCHKIT_UPDATE_COUNTER(arg0) \
do { \
	__asm__ volatile(".reference " FRENCHKIT_TYPEDEFS); \
	__dtrace_probe$frenchkit$update_counter$v1$696e74(arg0); \
	__asm__ volatile(".reference " FRENCHKIT_STABILITY); \
} while (0)
#define	FRENCHKIT_UPDATE_COUNTER_ENABLED() \
	({ int _r = __dtrace_isenabled$frenchkit$update_counter$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$frenchkit$update_counter$v1$696e74(int);
extern int __dtrace_isenabled$frenchkit$update_counter$v1(void);

#else

#define	FRENCHKIT_UPDATE_COUNTER(arg0) \
do { \
	} while (0)
#define	FRENCHKIT_UPDATE_COUNTER_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _FRENCHKITPROVIDER_H */
